num = int(input("digite um numero"))
print(f"o numero é {num}")
print (f"{num * 1}","\n")
print (f"{num * 2}","\n")
print (f"{num * 3}","\n")
print (f"{num * 4}","\n")
print (f"{num * 5}","\n")
print (f"{num * 6}","\n")
print (f"{num * 7}","\n")
print (f"{num * 8}","\n")
print (f"{num * 9}","\n")
print (f"{num * 10}","\n")